### ISSUE TITLE
Not able to login with my host username and password

### ISSUE THREAD

**Issue by sierxue** [dclong/docker-jupyterhub-ds#28]
I'm on Ubuntu 20.04.

After running the command given below, which is suggested in http://www.legendu.net/en/blog/my-docker-images/#usage,

```
   docker run -d --init \
    --hostname jupyterhub-ds \
    --log-opt max-size=50m \
    -p 8000:8000 \
    -p 5006:5006 \
    -e DOCKER_USER=$(id -un) \
    -e DOCKER_USER_ID=$(id -u) \
    -e DOCKER_PASSWORD=$(id -un) \
    -e DOCKER_GROUP_ID=$(id -g) \
    -e DOCKER_ADMIN_USER=$(id -un) \
    -v "$(pwd)":/workdir \
    -v "$(dirname $HOME)":/home_host \
    dclong/jupyterhub-ds /scripts/sys/init.sh
```

I can see the login page when I visit 127.0.0.1:8000. However, I'm not able to log in with my host username and password.

My password has only 4 characters consisting of only numbers. I wonder if this conflicts with the rule set in the docker image.

**Comment by dclong** [comment]
Both the user name and password for logging to JupyterHub is your host username. The password is control by the environment variable `DOCKER_PASSWORD`. As you can see in the command above, it is `id -un` by default, which is your host user name. 

There are 2 ways you can change the password. 
1. Pass in a different password via the option `-e DOCKER_PASSWORD` when you start a container. This way is NOT recommended as it is not secure. 
2. Change your password using `passwd` in a terminal after you login to JupyterHub. This is documented in https://www.legendu.net/en/blog/my-docker-images/#start-a-container (see highlighted in red) and is the recommended way.
