### ISSUE TITLE
About vim mode

### ISSUE THREAD

**Issue by sierxue** [dclong/docker-jupyterhub-ds#29]
I find that extension @axlair/jupyterlab_vim is prebuilt. However, I cannot use vim mode. How to use it?

**Comment by dclong** [comment]
The extension jupyterlab_vim is installed in the Docker image but it is disabled by default for a few reasons.

1. not all users are familiar with vim keybindings
2. there are still slight issues with jupyterlab_vim 

I consider jupyterlab_vim for advanced users only. If you do want to try it, you can enable it manually by running the following command in a terminal in JupyterLab. 
```
xinstall --sudo jvim --enable
```
which is essentially a convenient wrap of the official command
```
sudo jupyter labextension enable @axlair/jupyterlab_vim
```

**Comment by sierxue** [comment]
It worked smoothly. I greatly appreciate your quick responses and helps!
