### ISSUE TITLE
How to add a python module?

### ISSUE THREAD

**Issue by sierxue** [dclong/docker-jupyterhub-ds#31]
Sympy module is needed when I use the image. I tried two ways to install it, but only the second way works.

1. Install the module in a terminal after logged in. Command: `pip3 install sympy`; Output:
```
Requirement already satisfied: sympy in ./.local/lib/python3.8/site-packages (1.8)
Requirement already satisfied: mpmath>=0.19 in ./.local/lib/python3.8/site-packages (from sympy) (1.2.1)
```
1. Build a image from dclong/jupyterhub-ds with the following Dockerfile:
```
FROM dclong/jupyterhub-ds
# GIT: https://github.com/dclong/docker-jupyterhub-ds.git

RUN pip3 install --no-cache-dir \
    sympy
```
The image can be built successfully, and sympy module works.

**Comment by dclong** [comment]
Either way should work. At least I confirm that the first way works.

**Comment by sierxue** [comment]
Thanks! I made a silly mistake. In the first way, I forgot to reload the webpage after installation of the module.

**Comment by dclong** [comment]
Or you can restart (the kernel of) the notebook.

**Comment by sierxue** [comment]
Thanks, it's easier!
